name: salon
description: Beesoft LLC Salon app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  dio: ^4.0.0
  get_storage: ^2.0.2
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  fluttertoast: ^8.0.7
  lottie: ^1.0.1
  google_sign_in: ^5.0.4
  ionicons: ^0.1.2
  intl: ^0.17.0
  url_launcher: ^6.0.9
  rxdart: ^0.27.1
  timeago: ^3.1.0
  cached_network_image: ^3.0.0
  transparent_image: ^2.0.0
  like_button: ^2.0.2
  shape_of_view: ^1.0.2
  google_maps_flutter: ^2.0.6
  geolocator: ^7.3.1
  flutter_svg: ^0.22.0
  image_picker: ^0.8.2
  table_calendar: ^3.0.1
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  flutter_staggered_animations: ^1.0.0
  flutter_week_view: ^1.2.0
  firebase_storage: ^10.0.3
  camera: ^0.9.2+1
  flutter_facebook_auth: ^3.5.1
  qr_code_scanner: ^0.5.2
  custom_refresh_indicator: ^1.0.0
  slidable_button: ^1.0.2
  flutter_sticky_header: ^0.6.0
  webview_flutter: ^2.3.0
  permission_handler: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/img/
    - assets/svg/
    - assets/json/

  fonts:
    - family: "TenorSans"
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
          weight: 400
    - family: "Thasadith"
      fonts:
        - asset: assets/fonts/Thasadith-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Thasadith-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Thasadith-Bold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Thasadith-BoldItalic.ttf
          weight: 600
          style: italic
  uses-material-design: true